# Copyright 2019 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Template
metadata:
  name: "edp-admin-console"
  annotations:
    iconClass: "icon-spring"
    description: Openshift template for edp admin console
    template.openshift.io/provider-display-name: EPAM
    template.openshift.io/support-url: https://www.epam.com
objects:
  - apiVersion: authorization.openshift.io/v1
    kind: Role
    metadata:
      name: edp-resorses-admin
    rules:
      - apiGroups:
          - '*'
        attributeRestrictions: null
        resources:
          - businessapplications
          - applicationbranches
          - cdpipelines
        verbs:
          - get
          - create
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: edp-resorses-admin
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: edp-resorses-admin
    subjects:
      - kind: ServiceAccount
        name: admin-console
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: admin-console
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: "edp-admin-console"
      labels:
        app: "edp-admin-console"
    spec:
      replicas: 1
      selector:
        app: "edp-admin-console"
      strategy:
        activeDeadlineSeconds: 21600
        type: Rolling
        rollingParams:
          failurePolicy: Abort
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
      template:
        metadata:
          labels:
            app: "edp-admin-console"
        spec:
          serviceAccountName: "admin-console"
          containers:
            - name: "edp-admin-console"
              image: ${EDP_ADMIN_CONSOLE_VERSION}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
              livenessProbe:
                failureThreshold: 5
                initialDelaySeconds: 180
                periodSeconds: 20
                successThreshold: 1
                tcpSocket:
                  port: 8080
                timeoutSeconds: 5
              readinessProbe:
                failureThreshold: 5
                initialDelaySeconds: 60
                periodSeconds: 20
                successThreshold: 1
                tcpSocket:
                  port: 8080
                timeoutSeconds: 5
              resources:
                requests:
                  memory: 500Mi
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: HOST
                  value: ${HOST}
                - name: DNS_WILDCARD
                  value: ${DNS_WILDCARD}
                - name: KEYCLOAK_URL
                  value: ${KEYCLOAK_URL}
                - name: KEYCLOAK_CLIENT_ID
                  value: ${KEYCLOAK_CLIENT_ID}
                - name: KEYCLOAK_CLIENT_SECRET
                  value: ${KEYCLOAK_CLIENT_SECRET}
                - name: PG_HOST
                  value: "edp-install-wizard-db.${EDP_DEPLOY_PROJECT}"
                - name: PG_DATABASE
                  value: "edp-install-wizard-db"
                - name: PG_USER
                  valueFrom:
                    secretKeyRef:
                      name: admin-console-db
                      key: username
                - name: PG_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: admin-console-db
                      key: password
                - name: PG_PORT
                  value: "5432"
                - name: EDP_VERSION
                  value: ${EDP_VERSION}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: Route
    metadata:
      annotations:
        description: "Route for EDP Admin Console"
      name: "edp-admin-console"
      labels:
        app: "edp-admin-console"
    spec:
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: "edp-admin-console"
      port:
        targetPort: edp-admin-console
  - apiVersion: v1
    kind: Service
    metadata:
      name: "edp-admin-console"
      labels:
        app: "edp-admin-console"
    spec:
      ports:
        - name: "edp-admin-console"
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: "edp-admin-console"
      type: ClusterIP
parameters:
  - displayName: Image of EDP Admin Console container
    description: Image and tag that defines version of EDP Admin Console that will be deployed
    name: EDP_ADMIN_CONSOLE_VERSION
    value: "docker-registry-default.main.edp.projects.epam.com/infra/edp-admin-console:test"
    required: true
  - displayName: EDP Deploy Project
    name: EDP_DEPLOY_PROJECT
    value: ''
    required: true
  - displayName: Host name
    name: HOST
    value: ''
    required: true
  - displayName: DNS wildcard
    description: DNS wildcard of your project that should be specified during Openshift cluster installation
    name: DNS_WILDCARD
    value: ''
    required: true
  - displayName: Keycloak URL
    name: KEYCLOAK_URL
    value: ''
    required: true
  - displayName: Keycloak Client ID
    name: KEYCLOAK_CLIENT_ID
    value: ''
    required: true
  - displayName: Keycloak Client Secret
    name: KEYCLOAK_CLIENT_SECRET
    value: ''
    required: true
  - displayName: Version of EDP
    name: EDP_VERSION
    value: ''
    required: true