apiVersion: v2.edp.epam.com/v1alpha1
kind: Gerrit
metadata:
  name: gerrit
spec:
  type: "Gerrit"
  version: "{{ tools.gerrit.version }}"
  keycloakSpec:
    enabled: true
    url: "{{ tools.keycloak.web_url }}"
    realm: "{{ tools.keycloak.realm_name }}"
  volumes:
    - name: "data"
      storage_class: "{{ storage_class_name }}"
      capacity: "{{ tools.gerrit.volume_capacity }}"
  users:
{% for user in gerrit_super_admins %}
    - username: {{ user['username'] }}
      groups:
        - Administrators
{% endfor %}
{% for user in gerrit_admins %}
    - username: {{ user['username'] }}
      groups:
        - Administrators
{% endfor %}