{{- if eq .Values.edp.platform "kubernetes"  -}}
  {{-  $name := printf "%s-deploy" .Values.edp.name -}}
  {{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRoleBinding" "" $name).metadata}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{$name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edp-deploy-role-{{ .Values.edp.name }}
subjects:
  - kind: ServiceAccount
    name: edp
    namespace: {{ .Values.edp.name }}
  {{- end -}}
{{- end -}}