---
- name: "Get app settings from project-settings config map"
  command: |
   {{ ocadm }} -n {{ project_cicd }} get cm project-settings -o=jsonpath='{ .data.app\.settings\.json }'
  register: app_settings

- name: "Convert app settings json"
  set_fact:
    app_settings: "{{ app_settings.stdout | from_json }}"

- name: "Retrieve data from json"
  when: "item.name ==  project_name"
  set_fact:
    git_repo_url: "{{ item.git_repo_url }}"
    language: "{{ item.language }}"
    build_tool: "{{ item.build_tool }}"
    framework: "{{ item.framework }}"
    route: "{{ item.route }}"
    route_site: "{{ item.route_site | default('') }}"
    route_path: "{{ item.route_path | default('') }}"
    need_database: "{{ item.need_database }}"
    database: "{{ item.database | default('') }}"
    database_version: "{{ item.database_version | default('') }}"
    database_capacity: "{{ item.database_capacity | default('') }}"
    persistent_storage: "{{ item.persistent_storage | default('') }}"
  with_items: "{{ app_settings | list }}"