---
- name: "Set project_cicd variable"
  set_fact:
    project_cicd: "{{ lookup('env','PROJECT_CICD') }}"

- include_tasks: roles/common/tasks/manage-configmaps/retrieve-data-from-configmap.yml
  with_items:
    - { key_name: 'service\.settings\.json' }

- include_tasks: roles/common/tasks/manage-gerrit/push-template.yml