edp:
  name: "test"
  version: "epamedp/edp-install:latest"
  additionalToolsTemplate: "additional-tools"
  superAdmins: ""
  admins: ""
  viewers: ""
  dnsWildCard: ""
  storageClass: "gp2"
  devDeploy: "false"
jenkins:
  version: "epamedp/edp-jenkins:latest"
  volumeCapacity: "10Gi"
  stagesVersion: "master"
  pipelinesVersion: "master"
adminConsole:
  version: "epamedp/edp-admin-console:latest"
vcs:
  enabled: "false"
  toolName: ""
  groupName: ""
  sshPort: "22"
perf:
  enabled: "false"
  nodeId: ""
  url: ""