edpName: "test"
edpVersion: "epamedp/edp-install:latest"
edpSuperAdmins: ""
edpAdmins: ""
edpViewers: ""
dnsWildCard: ""
storageClass: "gp2"
gerritVersion: "2.16.10"
gerritVolumeCapacity: "5Gi"
jenkinsVersion: "epamedp/edp-jenkins:latest"
jenkinsVolumeCapacity: "10Gi"
nexusVersion: "3.15.1"
nexusVolumeCapacity: "10Gi"
sonarVersion: "7.6-community"
sonarVolumeCapacity: "5Gi"
sonarDbVolumeCapacity: "5Gi"
adminConsoleVersion: "epamedp/edp-admin-console:latest"
vcsIntegrationEnabled: "false"
vcsToolName: ""
vcsGroupName: ""
vcsSshPort: ""
perfIntegrationEnabled: "false"
perfNodeId: ""
perfUrl: ""