---
- name: "Set project_cicd variable"
  set_fact:
    project_cicd: "{{ lookup('env','PROJECT_CICD') }}"

- include_tasks: roles/common/tasks/manage-configmaps/retrieve-data-from-configmap.yml
  with_items:
    - { key_name: 'app\.settings\.json' }

- include_tasks: roles/common/tasks/manage-configmaps/retrieve-prerequisites-variable.yml

- include_tasks: roles/common/tasks/manage-ssh/generate-ssh-config.yml
  vars:
    gitlab_host: "{{ gitlab_group_hostname }}"

- include_tasks: roles/common/tasks/manage-gitlab/clone-repository.yml
  when: item_map.add_repo_strategy == "import"
  vars:
    git_repo_url: "{{ item_map.git_repo_url }}"

- include_tasks: roles/common/tasks/manage-gitlab/copy-repository.yml
  when: item_map.add_repo_strategy == "copy"
  vars:
    git_repo_url: "{{ item_map.git_repo_url }}"

- include_tasks: roles/common/tasks/manage-gerrit/set-up-gitlab-with-gerrit.yml
  vars:
    git_repo_url: "{{ item_map.git_repo_url }}"

- include_tasks: roles/common/tasks/manage-jenkins/trigger-job-provisioning.yml

- include_tasks: roles/common/tasks/manage-gerrit/push-template.yml