---
- name: "Get Openshift docker registry url"
  shell: "{{ ocadm }} -n default get route docker-registry -o jsonpath='{.spec.host}'"
  register: docker_registry

- name: "Set docker registry url variable"
  set_fact:
    docker_registry_url: "{{ docker_registry.stdout }}"

- name: "Get wildcard from user-settings cm"
  shell: |
   {{ ocadm }} -n {{ project_cicd }} get cm user-settings -o=jsonpath='{ .data.dns_wildcard }'
  register: wildcard

- name: "Set variable with wildcard"
  set_fact:
    dns_wildcard: "{{ wildcard.stdout }}"

- name: "Create directory for business apps templates"
  file:
    path: "{{ templates_dir }}/business-apps"
    state: directory

- name: "Set full app name"
  set_fact:
     full_app_name: "{{ framework | lower }}-{{ app_name }}"

- name: "Copying templates for {{ language }} {{ framework }} app"
  template:
    src: "business-applications/{{ language | lower }}/{{ item.src }}.j2"
    dest: "{{ templates_dir }}/business-apps/{{ item.dst }}.yml"
  with_items:
    - { src: "{{ framework | lower }}", dst: "{{ full_app_name }}" }
    - { src: "s2i-{{ framework | lower }}", dst: "s2i-{{ full_app_name }}" }

- name: "Import template for new business-app"
  command: |
    {{ ocadm }} -n {{ project_cicd }} apply -f {{ templates_dir }}/business-apps/{{ item }}.yml
  with_items:
    - "{{ full_app_name }}"
    - "s2i-{{ full_app_name }}"
  ignore_errors: true
