# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: "Get autouser secret name from user-settings cm"
  shell: |
   {{ ocadm }} -n {{ project_cicd }} get cm user-settings -o=jsonpath='{ .data.vcs_autouser_secret }'
  register: vcs_autouser_secret_name

- name: "Get autouser email from cicd projects secret"
  shell: >
   {{ ocadm }} -n {{ project_cicd }} get secret {{ vcs_autouser_secret_name.stdout }}
   --template={% raw %}'{{ index .data "username" }}'{% endraw %} | base64 --decode
  register: vcs_autouser_email

- name: "Get autouser password from cicd projects secret"
  shell: >
   {{ ocadm }} -n {{ project_cicd }} get secret {{ vcs_autouser_secret_name.stdout }}
   --template={% raw %}'{{ index .data "password" }}'{% endraw %} | base64 --decode
  register: vcs_autouser_password
  no_log: True

- name: "Set facts with VCS autouser credentials"
  set_fact:
     vcs_autouser_email: "{{ vcs_autouser_email.stdout }}"
     vcs_autouser_name: "{{ vcs_autouser_email.stdout.split(\"@\")[0] }}"
     vcs_autouser_password: "{{ vcs_autouser_password.stdout }}"

- name: "Get ssh key from cicd projects secret"
  shell: >
    {{ ocadm }} --namespace {{ project_cicd }} get secret {{ vcs_autouser_secret_name.stdout }}
    --template={% raw %}'{{ index .data "ssh-privatekey" }}'{% endraw %} | base64 --decode
  register: ssh_key
  no_log: True

- name: "Create file with key"
  copy:
    content: "{{ ssh_key.stdout }}"
    dest: "{{ target_vcs_keyfile }}"
    mode: 0400