# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: "Get Jenkins admin user token from secret"
  shell: >
   {{ ocadm }} -n {{ project_cicd }} get secret jenkins-token
   --template={% raw %}'{{ index .data "token" }}'{% endraw %} | base64 --decode
  register: jenkins_token
  no_log: True

- name: "Get gerrit ssh port"
  shell: |
    {{ ocadm }} -n {{ project_cicd }} get cm gerrit -o=jsonpath='{ .data.sshPort }'
  register: gerrit_ssh_port

- name: "Get user settings from config map"
  shell: |
   {{ ocadm }} -n {{ project_cicd }} get cm user-settings -o=json
  register: result

- set_fact:
    user_settings: "{{ result.stdout | from_json }}"
    tools: "{{ tools | combine({ 'jenkins': { 'password': jenkins_token.stdout }}, recursive=True) }}"

- set_fact:
    dns_wildcard: "{{ user_settings.data.dns_wildcard }}"
    projects_prefix: "{{ user_settings.data.projects_prefix }}"
    project_vcs_group_name_url: "{{ user_settings.data.vcs_group_name_url }}"
    vcs_tool: "{{ user_settings.data.vcs_tool_name | lower }}"
    gerrit_ssh_port: "{{ gerrit_ssh_port.stdout }}"
    project_vcs_hostname: "{{ user_settings.data.vcs_group_name_url | urlsplit('hostname') }}"
    project_vcs_group_path: "{{ user_settings.data.vcs_group_name_url | urlsplit('path') | regex_replace('^/{1}', '') }}"
    vcs_ssh_port: "{{ user_settings.data.vcs_ssh_port }}"
    oc_group_name: "{{ user_settings.data.oc_group_name }}"

- set_fact:
    project_vcs_hostname_url: "{{ user_settings.data.vcs_group_name_url | urlsplit('scheme') }}://{{ project_vcs_hostname }}"
