---
- name: "Get crumb from Jenkins"
  uri:
    url: http://jenkins.{{ project_cicd }}:8080/crumbIssuer/api/json
    method: GET
    user: admin
    password: "{{ tools.jenkins.password }}"
    force_basic_auth: yes
  register: crumb

- name: "Trigger job provisioning"
  uri:
    url: http://jenkins.{{ project_cicd }}:8080/job/Job-provisioning/build
    method: POST
    user: admin
    password: "{{ tools.jenkins.password }}"
    force_basic_auth: yes
    HEADER_Jenkins-Crumb: "{{ crumb.json.crumb }}"
    status_code: 201