---
- name: "Get gerrit-project-creator ssh key from secret"
  shell: >
    {{ ocadm }} -n {{ project_cicd }} get secret gerrit-project-creator
    --template={% raw %}'{{ index .data "id_project_creator_rsa" }}'{% endraw %} | base64 --decode
  register: gerrit_project_creator_ssh

- local_action: copy content={{ gerrit_project_creator_ssh.stdout }} dest={{ work_dir }}/gerrit_rsa mode=0400

- include_tasks: roles/common/tasks/manage-gitlab/get-gitlab-sshkey-from-secret.yml
  vars:
    target_file: "{{ work_dir }}/gitlab_rsa"

- name: "Create .ssh directory"
  file:
    path: ~/.ssh
    state: directory

- name: "Config ssh"
  copy:
    content: |
      Host gerrit*
        HostName gerrit.{{ project_cicd }}
        Port {{ gerrit_ssh_port }}
        User project-creator
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        IdentityFile {{ work_dir }}/gerrit_rsa
        IdentitiesOnly yes

      Host {{ gitlab_host }}
        HostName {{ gitlab_host }}
        User git
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        IdentityFile {{ work_dir }}/gitlab_rsa
        IdentitiesOnly yes
    dest: ~/.ssh/config
    force: yes

- name: "Create project in Gerrit"
  shell: "ssh gerrit.{{ project_cicd }} gerrit create-project {{ project_name }}"