---
- name: "Get gerrit-project-creator ssh key from secret"
  shell: >
    {{ ocadm }} -n {{ project_cicd }} get secret gerrit-project-creator
    --template={% raw %}'{{ index .data "id_project_creator_rsa" }}'{% endraw %} | base64 --decode
  register: gerrit_project_creator_ssh
  no_log: True

- name: "Create file with key"
  copy:
    content: "{{ gerrit_project_creator_ssh.stdout }}"
    dest: "{{ target_gerrit_keyfile }}"
    mode: 0400