# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

---
- include_tasks: roles/common/tasks/manage-openshift/update-replication-config.yml
  with_sequence: count=5

- name: "Save replication configmap to file"
  shell: |
    {{ ocadm }} get cm gerrit -n {{ project_cicd }} -o jsonpath='{.data.replication\.config}'
  register: replication_config

- local_action: copy content="{{ replication_config.stdout }}" dest="/tmp/replication.config"

- set_fact:
    gerrit_pod: |
                  for i in `{{ ocadm }} -n {{ project_cicd }} get pods --no-headers -o custom-columns=NAME:.metadata.name | \
                  egrep 'gerrit-[0-9]+'`; do pod_status=`{{ ocadm }} -n {{ project_cicd }} get pods $i -o jsonpath='{.status.phase}'`;\
                  if [[ $pod_status = 'Running' ]]; then echo $i; fi; done
    gerrit_manage: "ssh gerrit.{{ project_cicd }} gerrit"

- name: "Copy replication config to gerrit pod"
  shell: "{{ ocadm }} cp /tmp/replication.config {{ project_cicd }}/$({{ gerrit_pod }}):/var/gerrit/review_site/etc/replication.config"

- name: "Reload replication plugins"
  shell: "{{ gerrit_manage }} plugin reload replication"
