---
- include_tasks: roles/common/tasks/manage-openshift/update-replication-config.yml
  with_sequence: count=5

- name: "Save replication configmap to file"
  shell: |
    {{ ocadm }} get cm gerrit -n {{ project_cicd }} -o jsonpath='{.data.replication\.config}'
  register: replication_config

- local_action: copy content="{{ replication_config.stdout }}" dest="/tmp/replication.config"

- name: "Get Gerrit ssh port"
  shell: "{{ ocadm }} get svc gerrit -o=jsonpath='{.spec.ports[?(@.name==\"ssh\")].port}'"
  register: ssh_port

- set_fact:
    gerrit_pod: "{{ ocadm }} -n {{ project_cicd }} get pods --no-headers -o custom-columns=NAME:.metadata.name | egrep 'gerrit-[0-9]+'"
    gerrit_manage: "ssh gerrit.{{ project_cicd }} gerrit"
    gitlab_key_path: "{{ work_dir }}/gitlab-private.key"
    gerrit_key_path: "{{ work_dir }}/gerrit-private.key"

- name: "Copy replication config to gerrit pod"
  shell: "{{ ocadm }} cp /tmp/replication.config {{ project_cicd }}/$({{ gerrit_pod }}):/var/gerrit/review_site/etc/replication.config"

- include_tasks: roles/common/tasks/manage-gerrit/get-gerrit-credentials-from-secret.yml
  vars:
    target_gerrit_keyfile: "{{ gerrit_key_path }}"

- name: "Create .ssh directory"
  file:
    path: ~/.ssh
    state: directory

- name: "Config ssh"
  copy:
    content: |
      Host gerrit*
        HostName gerrit.{{ project_cicd }}
        Port {{ ssh_port.stdout }}
        User project-creator
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        IdentityFile {{ gerrit_key_path }}
        IdentitiesOnly yes
    dest: ~/.ssh/config
    force: yes

- name: "Reload replication plugins"
  shell: "{{ gerrit_manage }} plugin reload replication"
