---
- include_tasks: roles/common/tasks/manage-gerrit/create-gerrit-project.yml
  vars:
    gitlab_host: "{{ gitlab_hostname }}"

- include_tasks: roles/common/tasks/manage-gerrit/push-to-gerrit.yml
  vars:
    target_dir: "{{ work_dir }}/{{ name }}"

- include_tasks: roles/common/tasks/manage-gerrit/project-replication.yml
