{{- if not (lookup "v2.edp.epam.com/v1alpha1" "Jenkins" ".Values.edp.name" ".Values.jenkins.name").metadata }}
apiVersion: v2.edp.epam.com/v1alpha1
kind: Jenkins
metadata:
  name: {{.Values.jenkins.name}}
spec:
  edpSpec:
    dnsWildcard: "{{ .Values.edp.dnsWildCard }}"
    {{- if .Values.jenkins.pullSecrets}}
    imagePullSecrets:
      {{- range .Values.jenkins.pullSecrets }}
      - {{. -}}
      {{- end -}}
    {{end}}
  image: "{{.Values.jenkins.image}}"
  version: {{.Values.jenkins.version}}
  volumes:
    - name: "data"
      storageClass: "{{ .Values.jenkins.storageClass }}"
      capacity: "{{ .Values.jenkins.volumeCapacity }}"
  sharedLibraries:
    - name: "edp-library-stages"
      id: "Stages"
      repository: "{{ .Values.jenkins.sharedLibraryRepo.stages }}"
      version: "{{ .Values.jenkins.sharedLibraryVersion.stages }}"
    - name: "edp-library-pipelines"
      id: "Pipelines"
      repository: "{{ .Values.jenkins.sharedLibraryRepo.pipelines }}"
      version: "{{ .Values.jenkins.sharedLibraryVersion.pipelines }}"
  keycloakSpec:
    enabled: true
    realm: "{{ .Values.edp.name }}-edp"
{{end}}