# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

---
- include_tasks: roles/common/tasks/manage-openshift/retrieve-user-settings-from-configmap.yml

- include_tasks: roles/api/vcs/generate-ssh-config.yml

- name: "Clone projects repositories from gerrit"
  shell: >
   git clone ssh://project-creator@gerrit.{{ project_cicd }}:{{ gerrit_ssh_port }}/{{ item.name }} &&
   scp -p -P {{ gerrit_ssh_port }} project-creator@gerrit.{{ project_cicd }}:hooks/commit-msg {{ item.name }}/.git/hooks/
  args:
    chdir: "{{ templates_dir }}"
  with_items: "{{ app_map | list }}"

- name: "Create directory for deploy templates"
  file:
    path: "{{ templates_dir }}/{{ item.name }}/deploy-templates"
    state: directory
  with_items: "{{ app_map | list }}"

- name: "Create config map for business-applications"
  vars:
    app_name: "{{ item[0].name }}"
  template:
    src: deploy-config.j2
    dest: "{{ templates_dir }}/{{ item[0].name }}/deploy-templates/{{ item[0].name }}-deploy-config-{{ item[1].name | regex_search('[^-]+$') }}.yaml"
    force: no
  with_nested:
    - "{{ app_map | list }}"
    - "{{ env_map | list }}"

- include_tasks: push-template-each.yml
  with_items: "{{ app_map | list }}"