# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: "Get crumb from Jenkins"
  uri:
    url: http://jenkins.{{ project_cicd }}:8080/crumbIssuer/api/json
    method: GET
    user: admin
    password: "{{ tools.jenkins.password }}"
    force_basic_auth: yes
  retries: 5
  delay: 1
  register: crumb
  until: crumb.status == 200

- name: "Check if {{ job_name }} exists"
  uri:
    url: http://jenkins.{{ project_cicd }}:8080/job/{{ job_name }}/api/json
    method: GET
    user: admin
    password: "{{ tools.jenkins.password }}"
    force_basic_auth: yes
  retries: 5
  delay: 6
  register: output
  until: output.status == 200

- name: "Trigger job {{ job_name }}"
  uri:
    url: "http://jenkins.{{ project_cicd }}:8080/job/{{ job_name }}/build\
    {% if parameterized is defined %}WithParameters{% endif %}"
    method: POST
    user: admin
    password: "{{ tools.jenkins.password }}"
    force_basic_auth: yes
    headers:
      Jenkins-Crumb: "{{ crumb.json.crumb }}"
    status_code: 201
  retries: 5
  delay: 1
  register: output
  until: output.status == 201