# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: "Configure role mapping for master realm"
  uri:
    url: "{{ keycloak_base_url }}/admin/realms/master/identity-provider/instances/{{ tools.keycloak.realm_name }}/mappers"
    method: POST
    headers:
      Authorization: "Bearer {{ access_token }}"
      Content-Type: "application/json"
    body: "{{ lookup('template','roles/post-integration/templates/keycloak/role-mapper-for-idp.json.j2') | to_json }}"
    body_format: json
    status_code: 201
  with_items:
    -  { name: "create-realm", external_role: "master-create-realm", role: "create-realm" }
    -  { name: "impersonation", external_role: "realm-management.impersonation", role: "{{ tools.keycloak.realm_name }}-realm.impersonation" }
    -  { name: "manage-clients", external_role: "realm-management.manage-clients", role: "{{ tools.keycloak.realm_name }}-realm.manage-clients" }
    -  { name: "view-authorization", external_role: "realm-management.view-authorization", role: "{{ tools.keycloak.realm_name }}-realm.view-authorization" }
    -  { name: "view-events", external_role: "realm-management.view-events", role: "{{ tools.keycloak.realm_name }}-realm.view-events" }
    -  { name: "view-identity-providers", external_role: "realm-management.view-identity-providers", role: "{{ tools.keycloak.realm_name }}-realm.view-identity-providers" }
    -  { name: "view-realm", external_role: "realm-management.view-realm", role: "{{ tools.keycloak.realm_name }}-realm.view-realm" }
    -  { name: "view-users", external_role: "realm-management.view-users", role: "{{ tools.keycloak.realm_name }}-realm.view-users" }
