- name: "Install Keycloak proxy"
  shell: >
    {{ ocadm }} -n {{ project_cicd }} process -f {{ post_integration_dir }}/keycloak/proxy.yml
    -p UPSTREAM_RESOURCE={{ item.upstream_resource }}
    -p KEYCLOAK_WEB_URL={{ tools.keycloak.web_url }}
    -p REALM={{ tools.keycloak.realm_name }}
    -p CLIENT_ID={{ item.client_id }}
    -p REDIRECTION_URL={{ item.redirection_url }}
    -p ROLES={{ item.roles }}
    -p UPSTREAM_PORT={{ item.upstream_port }} | oc -n {{ project_cicd }} apply -f -