{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.edpName }}
roleRef:
  name: edp-deploy-role-{{ .Values.global.edpName }}
subjects:
- kind: ServiceAccount
  name: edp
  namespace: {{ .Values.global.edpName }}
userNames:
- system:serviceaccount:{{ .Values.global.edpName }}:edp
groupNames: []
{{- end -}}
