{{- if eq .Values.edp.platform "openshift" -}}
  {{- range .Values.edp.adminGroups -}}
    {{- if not (lookup "user.openshift.io/v1" "Group" "$.Values.edp.name" .)}}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: {{.}}
users:
      {{ range $.Values.edp.admins -}}
  - {{.}}
      {{end}}
    {{end}}
  {{end}}

  {{- range .Values.edp.developerGroups -}}
    {{- if not (lookup "user.openshift.io/v1" "Group" "$.Values.edp.name" .)}}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: {{.}}
users:
      {{ range $.Values.edp.developers -}}
  - {{.}}
      {{end}}
    {{end}}
  {{end}}
{{end}}