{{- if eq .Values.global.platform "openshift"  -}}
  {{- $name := printf "edp-%s-admin" .Values.global.edpName -}}
  {{- if not (lookup "rbac.authorization.k8s.io/v1" "RoleBinding" .Values.global.edpName $name).metadata}}
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: {{$name}}
roleRef:
  name: admin
subjects:
- kind: User
  name: admin
- kind: User
  name: system:serviceaccount:{{ .Values.global.edpName }}:edp
userNames:
- admin
- system:serviceaccount:{{ .Values.global.edpName }}:edp
groupNames: []
  {{- end -}}
{{- end -}}
