{{- if eq .Values.global.platform "openshift" -}}
  {{- range .Values.global.admins -}}
    {{- if not (lookup "user.openshift.io/v1" "User" "" .).metadata }}
---
apiVersion: user.openshift.io/v1
kind: User
identities: []
groups: []
metadata:
  name: {{.}}
      {{end}}
  {{end}}
{{end}}
