# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

kind: Template
apiVersion: v1
metadata:
  name: edp-cockpit
  annotations:
    description: |-
          The EDP-Cockpit panel.
    openshift.io/display-name: EDP Cockpit
    template.openshift.io/provider-display-name: EPAM
    template.openshift.io/support-url: https://www.epam.com
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: cockpit
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRole
  metadata:
    name: edp-cockpit
  rules:
  - apiGroups:
    - '*'
    attributeRestrictions: null
    resources:
    - projectrequests
    - projects
    - rolebindings
    verbs:
    - get
    - list
    - create
- apiVersion: authorization.openshift.io/v1
  kind: Role
  metadata:
    name: edp-cockpit
  rules:
  - apiGroups:
    - '*'
    attributeRestrictions: null
    resourceNames:
    - vcs-autouser
    - gerrit-admin
    - jenkins-token
    - keycloak-admin
    - keycloak-gerrit
    - gerrit-project-creator
    - keycloak
    - keycloak-parameters
    resources:
    - secrets
    verbs:
    - get
  - apiGroups:
    - "*"
    attributeRestrictions: null
    resourceNames: []
    resources:
    - jobs
    verbs:
    - list
    - get
    - create
    - patch
    - update
    - delete
  - apiGroups:
    - "*"
    attributeRestrictions: null
    resourceNames: []
    resources:
    - pods
    - pods/exec
    verbs:
    - list
    - get
    - create
  - apiGroups:
    - "*"
    attributeRestrictions: null
    resourceNames: []
    resources:
    - configmaps
    - routes
    - imagestreams
    - buildconfigs
    verbs:
    - list
    - get
    - create
    - patch
    - update
  - apiGroups:
    - "*"
    attributeRestrictions: null
    resourceNames: []
    resources:
    - templates
    - processedtemplates
    verbs:
    - get
    - create
- apiVersion: v1
  kind: Service
  metadata:
    name: edp-cockpit
    labels:
      app: edp-cockpit
  spec:
    ports:
    - name: edp-cockpit
      port: 8080
    selector:
      app: edp-cockpit
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for EDP Cockpit's https service.
      template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    name: edp-cockpit
    labels:
      app: edp-cockpit
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: edp-cockpit
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: edp-cockpit
    name: edp-cockpit
  spec:
    replicas: 1
    selector:
      app: edp-cockpit
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 1200
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: edp-cockpit
      spec:
        serviceAccountName: cockpit
        containers:
        - image: ${EDP_COCKPIT_VERSION}
          imagePullPolicy: Always
          name: edp-cockpit
          ports:
          - containerPort: 8080
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 5
          resources:
            requests:
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          env:
          - name: PROJECT_CICD
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPENSHIFT_TRUST_CERTIFICATES
            value: ${OPENSHIFT_TRUST_CERTIFICATES}
          - name: EDP_APPLICATION_TYPES
            valueFrom:
              configMapKeyRef:
                name: project-types
                key: app-types.json
          - name: EDP_AUTOTEST_TYPES
            valueFrom:
              configMapKeyRef:
                name: project-types
                key: autotest-types.json
          - name: EDP_SERVICE_TYPES
            valueFrom:
              configMapKeyRef:
                name: project-types
                key: service-types.json
          - name: MSRA_APP_QUICKSTART
            valueFrom:
              configMapKeyRef:
                name: msra
                key: app-quickstart.json
          - name: MSRA_AUTOTEST_QUICKSTART
            valueFrom:
              configMapKeyRef:
                name: msra
                key: autotest-quickstart.json
          - name: MSRA_ENV_QUICKSTART
            valueFrom:
              configMapKeyRef:
                name: msra
                key: env-quickstart.json
          - name: MSRA_SERVICE_QUICKSTART
            valueFrom:
              configMapKeyRef:
                name: msra
                key: service-quickstart.json
          - name: MSRA_MODIFIABLE_SERVICE_QUICKSTART
            valueFrom:
              configMapKeyRef:
                name: msra
                key: modifiable-service-quickstart.json
    triggers:
    - type: ConfigChange
parameters:
- displayName: Version of edp-cockpit
  name: EDP_COCKPIT_VERSION
  value: "docker-registry-default.main.edp.projects.epam.com/infra/edp-cockpit:master"
- displayName: Enable trust certificates
  name: OPENSHIFT_TRUST_CERTIFICATES
  value: "true"
