---
- name: Creates work directory
  file:
    path: "{{ post_integration_dir }}/{{ item }}"
    state: directory
  with_items:
      - "{{ tools.keys() }}"
- name: "Switching to CICD project"
  shell: "{{ ocadm }} project {{ project_cicd }}"

- name: "Get Gerrit ssh port"
  shell: "{{ ocadm }} get svc gerrit -o=jsonpath='{.spec.ports[?(@.name==\"ssh\")].port}'"
  register: ssh_port

- set_fact:
    jenkins_pod: "{{ ocadm }} get pods --no-headers -o custom-columns=NAME:.metadata.name | egrep 'jenkins-[0-9]+'"
    gerrit_ssh_port: "{{ ssh_port.stdout }}"
    gerrit_pod: "{{ ocadm }} get pods --no-headers -o custom-columns=NAME:.metadata.name | egrep 'gerrit-[0-9]+'"
    gerrit_db_pod: "{{ ocadm }} get pods --no-headers -o custom-columns=NAME:.metadata.name | egrep 'gerrit-db-[0-9]+'"
    gerrit_manage: "ssh -p {{ ssh_port.stdout }} gerrit.{{ project_cicd }} gerrit"
    gerrit_api_url: "http://gerrit.{{ project_cicd }}:8080/a"
    nexus_host: "nexus.{{ project_cicd }}"
    nexus_port: "8081"
    sonar_api_url: "http://sonar.{{ project_cicd }}:9000/api"
    gitlab_hostname: "{{ gitlab_group_name | urlsplit('hostname')}}"
    gitlab_group: "{{ gitlab_group_name | urlsplit('path')}}"

- include_tasks: check-deployment-health.yml
  with_items:
    - { project: '{{ project_cockpit }}', service: 'keycloak' }
    - { project: '{{ project_cicd }}', service: 'gerrit' }
    - { project: '{{ project_cicd }}', service: 'nexus' }
    - { project: '{{ project_cicd }}', service: 'sonar' }
    - { project: '{{ project_cicd }}', service: 'jenkins' }

- include_tasks: nexus-configuration.yml
- include_tasks: sonar-configuration.yml
- include_tasks: keycloak-configuration.yml
- include_tasks: gerrit-configuration.yml
- include_tasks: jenkins-configuration.yml

- include_tasks: check-deployment-health.yml
  with_items:
    - { project: '{{ project_cockpit }}', service: 'keycloak' }
    - { project: '{{ project_cockpit }}', service: 'edp-cockpit' }
    - { project: '{{ project_cicd }}', service: 'gerrit' }
    - { project: '{{ project_cicd }}', service: 'nexus' }
    - { project: '{{ project_cicd }}', service: 'sonar' }
    - { project: '{{ project_cicd }}', service: 'jenkins' }
