# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

---
- include_tasks: keycloak-configuration.yml

- include_tasks: check-cr-health.yml
  with_items:
    - { project: '{{ project_cicd }}', component: 'gerrits.v2.edp.epam.com', name: 'gerrit' }

- name: "Get Gerrit ssh port"
  shell: "{{ ocadm }} -n {{ project_cicd }} get svc gerrit -o=jsonpath='{.spec.ports[?(@.name==\"ssh\")].port}'"
  register: ssh_port

- set_fact:
    gerrit_ssh_port: "{{ ssh_port.stdout }}"

- name: "Create config map with Gerrit node port"
  shell: "{{ ocadm }} -n {{ project_cicd }} create cm gerrit --from-literal=sshPort={{ gerrit_ssh_port }}"

- name: Creates directory for GitServer templates
  file:
    path: "{{ templates_dir }}/git_server"
    state: directory

- name: "Copy Gerrit GitServer template"
  template:
    src: "gerrit-server.yaml"
    dest: "{{ templates_dir }}/git_server/gerrit-server.yaml"

- include_tasks: check-cr-health.yml
  with_items:
    - { project: '{{ project_cicd }}', component: 'gerrits.v2.edp.epam.com', name: 'gerrit'  }
    - { project: '{{ project_cicd }}', component: 'sonars.v2.edp.epam.com', name: 'sonar'  }
    - { project: '{{ project_cicd }}', component: 'nexus.v2.edp.epam.com', name: 'nexus'  }
    - { project: '{{ project_cicd }}', component: 'jenkins.v2.edp.epam.com', name: 'jenkins' }

- include_tasks: admin-console-configuration.yaml

- include_tasks: check-cr-health.yml
  with_items:
    - { project: '{{ project_cicd }}', component: 'adminconsoles.v2.edp.epam.com', name: 'edp-admin-console' }

- name: "Install Gerrit GitServer CR"
  command: |
    {{ ocadm }} -n {{ project_cicd }} apply -f {{ templates_dir }}/git_server/gerrit-server.yaml
  register: result
  ignore_errors: true
  changed_when: '"already" not in result.stderr'
  failed_when:
    - 'result.rc != 0'
    - '"already" not in result.stderr'
  no_log: true

- include_tasks: check-cr-health.yml
  with_items:
    - { project: '{{ project_cicd }}', component: 'gerrits.v2.edp.epam.com', name: 'gerrit'  }
    - { project: '{{ project_cicd }}', component: 'sonars.v2.edp.epam.com', name: 'sonar'  }
    - { project: '{{ project_cicd }}', component: 'nexus.v2.edp.epam.com', name: 'nexus'  }
    - { project: '{{ project_cicd }}', component: 'adminconsoles.v2.edp.epam.com', name: 'edp-admin-console' }
    - { project: '{{ project_cicd }}', component: 'jenkins.v2.edp.epam.com', name: 'jenkins' }

- include_tasks: check-deployment-health.yml
  with_items:
    - { project: '{{ project_cicd }}', service: 'gerrit' }
    - { project: '{{ project_cicd }}', service: 'nexus' }
    - { project: '{{ project_cicd }}', service: 'sonar' }
    - { project: '{{ project_cicd }}', service: 'jenkins' }
    - { project: '{{ project_cicd }}', service: 'edp-admin-console' }