--- # Gerrit post installation
- name: "Check integration job {{ item }} is finished"
  shell: "\
    {{ ocadm }} -n {{ project_cicd }} get pods --show-all -o json |
    jq -r '.items[] | select (.metadata.name | startswith(\"{{ item }}\"))| .status.phase'"
  register: result
  until: result.stdout == "Succeeded"
  retries: 30
  delay: 60
  with_items:
      - gerrit-integration
      - sonar-integration
      - nexus-integration

- name: "Enabling OAUTH for Gerrit"
  shell: "{{ ocadm }} -n {{ project_cicd }} set env dc gerrit AUTH_TYPE='OAUTH'"
  when: lookup('env', 'DISABLE_GERRIT_OAUTH') != 'true'

- name: "Redeploy Jenkins pod"
  shell: |
   {{ ocadm }} rollout latest jenkins -n {{ project_cicd }}

- name: "Check health of {{ item.service }} deployment in project {{ item.project }}"
  shell: "{{ ocadm }} -n {{ item.project }} rollout status dc/{{ item.service }}"
  register: result
  with_items:
      - { project: '{{ project_cicd }}', service: 'jenkins' }
      - { project: '{{ project_cicd }}', service: 'gerrit' }
      - { project: '{{ project_cicd }}', service: 'nexus' }
      - { project: '{{ project_cicd }}', service: 'sonar' }
      - { project: '{{ project_cockpit }}', service: 'edp-cockpit' }
      - { project: '{{ project_cockpit }}', service: 'keycloak' }

- include_tasks: keycloak_configuration.yml
- include_tasks: gitlab_gerrit_configuration.yml
