---
- include_tasks: roles/common/tasks/manage-gitlab/clone-repository.yml

- name: "Get gerrit ssh port"
  shell: "{{ ocadm }} -n {{ project_cicd }} get configMap gerrit -o=jsonpath={.data.sshPort}"
  register: "ssh_port"

- include_tasks: roles/common/tasks/manage-gerrit/create-gerrit-project.yml
  vars:
    gerrit_ssh_port: "{{ ssh_port.stdout }}"
    gitlab_host: "{{ gitlab_hostname }}"

- include_tasks: roles/common/tasks/manage-gerrit/push-to-gerrit.yml
  vars:
    gerrit_ssh_port: "{{ ssh_port.stdout }}"
    target_dir: "{{ work_dir }}/{{ project_name }}"

- include_tasks: roles/common/tasks/manage-gerrit/project-replication.yml
