# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Template
labels:
  template: add-application
metadata:
  name: add-application
  annotations:
    description: |-
          EDP add-application configuration to be applied.
          NOTE: You must have CI tools available in your cluster to use this template.
    iconClass: icon-jenkins
    openshift.io/display-name: Add an application
    tags: ci-cd
    template.openshift.io/documentation-url: https://kb.epam.com/display/EPMDEDP/EPMD-EDP+Home
    template.openshift.io/long-description: This template add application for letting EDP know about it.
    template.openshift.io/provider-display-name: EPAM
    template.openshift.io/support-url: https://www.epam.com
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: add-application-${NAME}
  spec:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 3600
    template:
      metadata:
        name: add-application
      spec:
        containers:
        - name: add-application
          image: ${DOCKER_IMAGE}
          imagePullPolicy: Always
          command:
            - "ansible-playbook"
            - "-v"
            - "-i"
            - "localhost,"
            - "-e ocadm=oc"
            - "-e ansible_connection=local"
            - "-e app_name=${NAME}"
            - "ansible-playbooks/add-business-application.yml"
          env:
          - name: PROJECT_CICD
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        restartPolicy: Never
        serviceAccountName: cockpit
      volumes:
        - name: user-settings
          configMap:
            name: user-settings
    backoffLimit: 1
parameters:
- displayName: Name of an application
  description: Type of an application to add
  name: NAME
  value: "app-name"