apiVersion: v1
kind: Template
labels:
  template: add-service
metadata:
  name: add-service
  annotations:
    description: |-
          EDP add-service configuration to be applied.
          NOTE: You must have Ci tools available in your cluster to use this template.
    iconClass: icon-jenkins
    openshift.io/display-name: Add service
    tags: ci-cd
    template.openshift.io/documentation-url: https://kb.epam.com/display/EPMDEDP/EPMD-EDP+Home
    template.openshift.io/long-description: This template add service for letting EDP know about it.
    template.openshift.io/provider-display-name: EPAM
    template.openshift.io/support-url: https://www.epam.com
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: add-service-${NAME}
  spec:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 300
    template:
      metadata:
        name: add-service
      spec:
        containers:
        - name: add-service
          image: ${DOCKER_IMAGE}
          imagePullPolicy: Always
          command:
            - "ansible-playbook"
            - "-v"
            - "-i"
            - "localhost,"
            - "-e ocadm=oc"
            - "-e ansible_connection=local"
            - "-e service_name=${NAME}"
            - "ansible-playbooks/add-service.yml"
          env:
          - name: PROJECT_CICD
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        restartPolicy: Never
        serviceAccountName: cockpit                
    backoffLimit: 1
parameters:
- displayName: Service alias
  description: Name for service
  name: NAME
  value: "service"
  required: true