# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

kind: Template
apiVersion: v1
metadata:
  name: edp
  annotations:
    description: |-
          Template for deploying EPAM Delivery Platform (EDP) aka "The Rocket" tools
    openshift.io/display-name: EDP - The Rocket
    template.openshift.io/provider-display-name: EPAM
    template.openshift.io/support-url: https://www.epam.com
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${EDP_NAME}-edp-deploy
  spec:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 3600
    template:
      metadata:
        name: edp-deploy
      spec:
        securityContext:
          runAsUser: 1000
        restartPolicy: Never
        serviceAccount: edp
        containers:
        - image: ${EDP_VERSION}
          imagePullPolicy: Always
          name: edp-deploy
          env:
          - name: DEPLOY-PROJECT
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          command:
            - "ansible-playbook"
            - "--tags=${APPS_TO_INSTALL}"
            - "-v"
            - "-i"
            - "localhost,"
            - "-e edp_name=${EDP_NAME}"
            - "-e additional_tools_template_name=${ADDITIONAL_TOOLS_TEMPLATE_NAME}"
            - "-e ocadm=oc"
            - "-e ansible_connection=local"
            - "-e super_admin_users=${EDP_SUPER_ADMINS}"
            - "-e admin_users=${EDP_ADMINS}"
            - "-e view_users=${EDP_VIEWERS}"
            - "-e edp_version=${EDP_VERSION}"
            - "-e dns_wildcard=${DNS_WILDCARD}"
            - "-e storage_class_name=${STORAGE_CLASS_NAME}"
            - "-e jenkins_fs_type=${JENKINS_FS_TYPE}"
            - "-e jenkins_host_path_volume=${JENKINS_HOST_PATH_VOLUME}"
            - "-e jenkins_volume_capacity=${JENKINS_VOLUME_CAPACITY}"
            - "-e jenkins_maven_cache_volume_capacity=${JENKINS_MAVEN_CACHE_VOLUME_CAPACITY}"
            - "-e jenkins_frontend_image=${JENKINS_FRONTEND_IMAGE}"
            - "-e jenkins_backend_maven_image=${JENKINS_BACKEND_MAVEN_IMAGE}"
            - "-e jenkins_backend_gradle_image=${JENKINS_BACKEND_GRADLE_IMAGE}"
            - "-e jenkins_image_version=${JENKINS_IMAGE_VERSION}"
            - "-e nexus_version=${NEXUS_VERSION}"
            - "-e nexus_volume_capacity=${NEXUS_VOLUME_CAPACITY}"
            - "-e vcs_integration_enabled=${VCS_INTEGRATION_ENABLED}"
            - "-e vcs_tool_name=${VCS_TOOL_NAME}"
            - "-e vcs_group_name=${VCS_GROUP_NAME_URL}"
            - "-e vcs_ssh_port=${VCS_SSH_PORT}"
            - "-e perf_integration_enabled=${PERF_INTEGRATION_ENABLED}"
            - "-e perf_node_id=${PERF_NODE_ID}"
            - "-e perf_url=${PERF_URL}"
            - "-e admin_console_version=${ADMIN_CONSOLE_VERSION}"
            - "ansible-playbooks/install.yml"
parameters:
- displayName: Name for EDP tenant
  description: Unique name for EDP tenant which will be used during installation
  name: EDP_NAME
  value: "test"
  required: true
- displayName: DNS wildcard
  description: DNS wildcard of your project that should be specified during Openshift cluster installation
  name: DNS_WILDCARD
  value: ""
  required: true
- displayName: Name of the template for non mandatory tools of EDP
  description: Template that will be used during EDP provisioning for deploying additional tools like Sonar, GitServe etc.
  name: ADDITIONAL_TOOLS_TEMPLATE_NAME
  value: "additional-tools"
  required: true
- displayName: Storage class name
  description: Storage class name to consume by every EDP tool
  name: STORAGE_CLASS_NAME
  value: "efs"
  required: true
- displayName: Image of EDP container
  description: Image and tag that defines version of EDP that will be deployed
  name: EDP_VERSION
  value: "docker-registry-default.main.edp.projects.epam.com/infra/edp-test:test"
- displayName: EDP Super Admins
  description: Users that will have full admin permissions in this EDP tenant (comma-separated, NO spaces)
  name: EDP_SUPER_ADMINS
  value: ""
- displayName: EDP Admins
  description: Users that will have full admin permissions in this EDP tenant except META-projects (comma-separated, NO spaces)
  name: EDP_ADMINS
  value: ""
- displayName: EDP Viewers
  description: Users that will have view permissions in this EDP tenant except META-projects (comma-separated, NO spaces)
  name: EDP_VIEWERS
  value: ""
- displayName: Applications to install
  description: For separate installation, defines what tools will be deployed during installation. For now it can be jenkins,nexus,gerrit,sonar.
  name: APPS_TO_INSTALL
  value: "all"
#Jenkins parameters
- displayName: Jenkins filesystem type
  description: Allowed values only 'pvc'(Persistant volume claim) or 'hostpath'
  name: JENKINS_FS_TYPE
  value: "pvc"
  required: true
- displayName: Jenkins HostPath volume path
  description: Define it in case you chose 'hostpath' on the previous field. Otherwise, it should be ignored.
  name: JENKINS_HOST_PATH_VOLUME
  value: "/opt/data/jenkins"
- displayName: Volume Capacity
  description: Volume space available for Jenkins data
  name: JENKINS_VOLUME_CAPACITY
  value: 10Gi
  required: true
- displayName: Maven Cache Volume Capacity
  description: Volume space available for maven cache data
  name: JENKINS_MAVEN_CACHE_VOLUME_CAPACITY
  required: true
  value: 10Gi
- displayName: Frontend docker image.
  name: JENKINS_FRONTEND_IMAGE
  value: "openshift/jenkins-agent-nodejs-8-centos7:v3.10"
- displayName: Jenkins EDP docker image.
  name: JENKINS_IMAGE_VERSION
  value: "docker-registry-default.main.edp.projects.epam.com/infra/edp-jenkins:latest"
- displayName: Backend docker image.
  name: JENKINS_BACKEND_MAVEN_IMAGE
  value: "openshift/jenkins-agent-maven-35-centos7:v3.10"
- displayName: Backend gradle docker image.
  name: JENKINS_BACKEND_GRADLE_IMAGE
  value: "epamedp/jenkins-slave-gradle-openshift:1.10.0"
#Nexus parameters
- displayName: Sonatype Nexus version
  name: NEXUS_VERSION
  value: "3.15.1"
- displayName: Volume Space for Nexus
  description: Volume space available for Sonatype Nexus data
  name: NEXUS_VOLUME_CAPACITY
  value: 10Gi
#Sonar parameters
- displayName: SonarQube version
  value: "7.6-community"
  name: SONAR_VERSION
- description: Volume space available for SonarQube
  displayName: SonarQube Volume Capacity
  name: SONAR_VOLUME_CAPACITY
  value: 5Gi
- description: Volume space available for SonarQube Database
  displayName: SonarQube database Volume Capacity
  name: SONAR_DB_CAPACITY
  value: 5Gi
#VCS parameters
- displayName: Does intergration with VCS is enabled(true/false)
  description: Defines whether integration with VCS is enabled or not
  name: VCS_INTEGRATION_ENABLED
  value: "false"
  required: true
- displayName: Preferred Version Control System
  description: VCS tool which will be consumed during EDP installation. Currently supported Gitlab and Bitbucket
  name: VCS_TOOL_NAME
  value: ""
- displayName: VCS group name URL
  description: VCS URL to the project group. For example 'https://git.epam.com/epmd-edp/temp'
  name: VCS_GROUP_NAME_URL
  value: ""
- displayName: VCS ssh port
  name: VCS_SSH_PORT
  value: "22"
#Perf integration parameters
- displayName: Does intergration with Perf is enabled(true/false)
  description: Defines whether integration with Perf is enabled or not
  name: PERF_INTEGRATION_ENABLED
  value: "false"
  required: true
- displayName: Perf node ID
  description: Perf node ID given after project registration
  name: PERF_NODE_ID
  value: ""
- displayName: Perf URL
  description: Perf URL location
  name: PERF_URL
  value: ""
- displayName: Version of Admin Console
  name: ADMIN_CONSOLE_VERSION
  value: "docker-registry.default.svc:5000/edp-cicd-delivery/edp-admin-console:master"