# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

kind: Template
apiVersion: v1
metadata:
  name: edp
  annotations:
    description: |-
          Template for deploying EPAM Delivery Platform (EDP) aka "The Rocket" tools
    openshift.io/display-name: EDP - The Rocket
    template.openshift.io/provider-display-name: EPAM
    template.openshift.io/support-url: https://www.epam.com
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: edp-deploy${PROJECTS_SUFFIX}
  spec:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 3600
    template:
      metadata:
        name: edp-deploy
      spec:
        restartPolicy: Never
        serviceAccount: edp
        containers:
        - image: ${EDP_VERSION}
          imagePullPolicy: Always
          name: edp-deploy
          command:
            - "ansible-playbook"
            - "--tags=${APPS_TO_INSTALL}"
            - "-v"
            - "-i"
            - "localhost,"
            - "-e projects_suffix=${PROJECTS_SUFFIX}"
            - "-e ocadm=oc"
            - "-e ansible_connection=local"
            - "-e edp_version=${EDP_VERSION}"
            - "-e dns_wildcard=${DNS_WILDCARD}"
            - "-e storage_class_name=${STORAGE_CLASS_NAME}"
            - "-e gerrit_version=${GERRIT_VERSION}"
            - "-e gerrit_auth_type=${GERRIT_AUTH_TYPE}"
            - "-e gerrit_volume_capacity=${GERRIT_DATA_CAPACITY}"
            - "-e gerrit_volume_db_capacity=${GERRIT_DB_CAPACITY}"
            - "-e jenkins_enable_oauth=${JENKINS_ENABLE_OAUTH}"
            - "-e jenkins_fs_type=${JENKINS_FS_TYPE}"
            - "-e jenkins_host_path_volume=${JENKINS_HOST_PATH_VOLUME}"
            - "-e jenkins_volume_capacity=${JENKINS_VOLUME_CAPACITY}"
            - "-e jenkins_maven_cache_volume_capacity=${JENKINS_MAVEN_CACHE_VOLUME_CAPACITY}"
            - "-e jenkins_frontend_image=${JENKINS_FRONTEND_IMAGE}"
            - "-e jenkins_backend_image=${JENKINS_BACKEND_IMAGE}"
            - "-e jenkins_image_version=${JENKINS_IMAGE_VERSION}"
            - "-e nexus_version=${NEXUS_VERSION}"
            - "-e nexus_volume_capacity=${NEXUS_VOLUME_CAPACITY}"
            - "-e sonar_version=${SONAR_VERSION}"
            - "-e sonar_volume_capacity=${SONAR_VOLUME_CAPACITY}"
            - "-e sonar_volume_db_capacity=${SONAR_DB_CAPACITY}"
            - "-e cockpit_version=${EDP_COCKPIT_VERSION}"
            - "-e vcs_tool_name=${VCS_TOOL_NAME}"
            - "-e vcs_oauth_app_id=${VCS_OAUTH_APP_ID}"
            - "-e vcs_oauth_app_secret=${VCS_OAUTH_APP_SECRET}"
            - "-e vcs_auto_user_secret=${VCS_AUTO_USER_SECRET}"
            - "-e vcs_group_name=${VCS_GROUP_NAME_URL}"
            - "-e keycloak_image=${KEYCLOAK_IMAGE}"
            - "-e keycloak_volume_db_capacity=${KEYCLOAK_DB_CAPACITY}"
            - "-e keycloak_realm_name=${KEYCLOAK_REALM_NAME}"
            - "-e keycloak_admin_user_secret=${KEYCLOAK_ADMIN_USER_SECRET}"
            - "ansible-playbooks/install.yml"
parameters:
- displayName: DNS wildcard
  description: DNS wildcard of your project that should be specified during Openshift cluster installation
  name: DNS_WILDCARD
  value: ""
  required: true
- displayName: Storage class name
  description: Storage class name to consume by every EDP tool
  name: STORAGE_CLASS_NAME
  value: "glusterfs-storage"
  required: true
- displayName: Preferred Version Control System
  description: VCS tool which will be consumed during EDP installation. Currently supported Gitlab and Bitbucket
  name: VCS_TOOL_NAME
  value: "Gitlab"
  required: true
- displayName: Image of EDP container
  description: Image and tag that defines version of EDP that will be deployed
  name: EDP_VERSION
  value: "docker-registry-default.main.edp.projects.epam.com/infra/edp-test:test"
- displayName: Suffix for projects
  description: Suffix that will be added to projects created by EDP Platform
  name: PROJECTS_SUFFIX
  value: "test"
- displayName: Applications to install
  description: For separate installation, defines what tools will be deployed during installation. For now it can be jenkins,nexus,gerrit,sonar,edp-cockpit.
  name: APPS_TO_INSTALL
  value: "all"
#Gerrit parameters
- displayName: Gerrit version
  value: "2.14.8"
  name: GERRIT_VERSION
- displayName: Gerrit Volume Capacity
  description: Volume space available for Gerrit data
  name: GERRIT_DATA_CAPACITY
  value: 5Gi
  required: true
- displayName: Gerrit database Volume Capacity
  description: Volume space available for Gerrit DB
  name: GERRIT_DB_CAPACITY
  value: 5Gi
  required: true
- displayName: To be removed after merge
  name: GERRIT_JOB_VERSION
  value: who-cares
- displayName: Gerrit Auth Type
  description: Can be either DEVELOPMENT_BECOME_ANY_ACCOUNT or OAUTH
  value: "OAUTH"
  name: GERRIT_AUTH_TYPE
#Jenkins parameters
- displayName: Jenkins filesystem type
  description: Allowed values only 'gluster' or 'hostpath'
  name: JENKINS_FS_TYPE
  value: "gluster"
  required: true
- displayName: Jenkins HostPath volume path
  description: Define it in case you chose 'hostpath' on the previous field. Otherwise, it should be ignored.
  name: JENKINS_HOST_PATH_VOLUME
  value: "/opt/data/jenkins"
- displayName: Enable OAuth in Jenkins
  description: Whether to enable OAuth OpenShift integration. If false, the static
    account 'admin' will be initialized with the password 'password'.
  name: JENKINS_ENABLE_OAUTH
  value: "false"
- displayName: Volume Capacity
  description: Volume space available for Jenkins data
  name: JENKINS_VOLUME_CAPACITY
  value: 10Gi
  required: true
- displayName: Maven Cache Volume Capacity
  description: Volume space available for maven cache data
  name: JENKINS_MAVEN_CACHE_VOLUME_CAPACITY
  required: true
  value: 10Gi
- displayName: Frontend docker image.
  name: JENKINS_FRONTEND_IMAGE
  value: "docker-registry-default.main.edp.projects.epam.com/infra/edp-ui-slave:latest"
- displayName: Jenkins EDP docker image.
  name: JENKINS_IMAGE_VERSION
  value: "docker-registry-default.main.edp.projects.epam.com/infra/edp-jenkins:latest"
- displayName: Backend docker image.
  name: JENKINS_BACKEND_IMAGE
  value: "openshift/jenkins-slave-maven-centos7"
#Nexus parameters
- displayName: Sonatype Nexus version
  name: NEXUS_VERSION
  value: "3.6.2"
- displayName: Volume Space for Nexus
  description: Volume space available for Sonatype Nexus data
  name: NEXUS_VOLUME_CAPACITY
  value: 5Gi
#Sonar parameters
- displayName: SonarQube version
  value: "7.1"
  name: SONAR_VERSION
- description: Volume space available for SonarQube
  displayName: SonarQube Volume Capacity
  name: SONAR_VOLUME_CAPACITY
  value: 5Gi
- description: Volume space available for SonarQube Database
  displayName: SonarQube database Volume Capacity
  name: SONAR_DB_CAPACITY
  value: 5Gi
#EDP Cockpit parameters
- displayName: Version of edp-cockpit
  name: EDP_COCKPIT_VERSION
  value: "docker-registry-default.main.edp.projects.epam.com/infra/edp-cockpit:SNAPSHOT"
#VCS parameters
- displayName: Gerrit Application ID
  description: Gerrit Application ID fot OAuth integration with VCS only if GERRIT_AUTH_TYPE set to OAUTH
  name: VCS_OAUTH_APP_ID
  value: ""
- displayName: Gerrit Application Secret
  description: Gerrit Application Secret fot OAuth integration with VCS only if GERRIT_AUTH_TYPE set to OAUTH
  name: VCS_OAUTH_APP_SECRET
  value: ""
- displayName: Git autouser secret name
  description: Git autouser secret name from prerequisites
  name: VCS_AUTO_USER_SECRET
  value: auto-epmc-java-vcs-with-ssh
  required: true
- displayName: VCS group name URL
  description: VCS URL to the project group. For example 'https://git.epam.com/epmd-edp/temp'
  name: VCS_GROUP_NAME_URL
  value: "https://git.epam.com/epmd-edp/temp"
  required: true
#Keycloak parameters
- displayName: Keycloak version
  name: KEYCLOAK_IMAGE
  value: "jboss/keycloak:3.4.3.Final"
- displayName: Keycloak database Volume Capacity
  description: Volume space available for Keycloak Database
  name: KEYCLOAK_DB_CAPACITY
  value: 2Gi
- displayName: Keycloak admin user secret name
  description: Keycloak admin user secret name from prerequisites
  name: KEYCLOAK_ADMIN_USER_SECRET
  value: keycloak
  required: true
- displayName: Keycloak realm name
  description: Realm name for Keycloak
  name: KEYCLOAK_REALM_NAME
  value: CI
