# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

kind: Template
apiVersion: v1
metadata:
  name: edp-preinstall
  annotations:
    description: |-
          Template for deploing service account and provide it with grants that is needed to deploy EPAM Delivery Platform (EDP) aka "The Rocket" tools
    openshift.io/display-name: EDP - The Rocket(SYSTEM)
    template.openshift.io/provider-display-name: EPAM
    template.openshift.io/support-url: https://www.epam.com
objects:
- apiVersion: v1
  kind: Project
  metadata:
    annotations:
      openshift.io/display-name: System project for EDP deployment
    name: ${PROJECT}
  spec:
    finalizers:
    - openshift.io/origin
    - kubernetes
- apiVersion: authorization.openshift.io/v1
  kind: RoleBinding
  metadata:
    name: edp-${PROJECT}-admin
    namespace: ${PROJECT}
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: ${USERNAME}
  - kind: User
    name: system:serviceaccount:${PROJECT}:edp
  userNames:
  - ${USERNAME}
  - system:serviceaccount:${PROJECT}:edp
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: edp
    namespace: ${PROJECT}
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRole
  metadata:
    annotations:
      openshift.io/description: Role for EDP service account that allows to deploy EPAM Delivery Platform (EDP) aka "The Rocket" tools
      openshift.io/reconcile-protect: "false"
    name: edp-deploy-role
  rules:
  - apiGroups:
    - "*"
    attributeRestrictions: null
    resources:
    - namespaces
    verbs:
    - get
    - list
    - create
    - patch
  - apiGroups:
    - ""
    - network.openshift.io
    attributeRestrictions: null
    resources:
    - ""
    verbs:
    - list
    - get
  - apiGroups:
    - ""
    - network.openshift.io
    attributeRestrictions: null
    resources:
    - netnamespaces
    verbs:
    - get
    - update
  - apiGroups:
    - ""
    - image.openshift.io
    attributeRestrictions: null
    resources:
    - imagestreamimages
    - imagestreammappings
    - imagestreams
    - imagestreamtags
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    - image.openshift.io
    attributeRestrictions: null
    resources:
    - imagestreams/layers
    verbs:
    - get
  - apiGroups:
    - '*'
    attributeRestrictions: null
    resources:
    - clusterrolebindings
    verbs:
    - delete
  - apiGroups:
    - "*"
    attributeRestrictions: null
    resources:
    - templates
    - processedtemplates
    - rolebindings
    - roles
    - clusterroles
    - clusterrolebindings
    - projectrequests
    - projects
    - namespaces
    - pods
    - pods/exec
    - groups
    - users
    - securitycontextconstraints
    - podsecuritypolicies
    - pods/portforward
    - jobs
    - configmaps
    - routes
    - imagestreams
    - buildconfigs
    verbs:
    - get
    - list
    - create
  - apiGroups:
    - '*'
    attributeRestrictions: null
    resources:
    - storageclasses
    verbs:
    - get
    - list
  - apiGroups:
    - '*'
    attributeRestrictions: null
    resources:
    - configmaps
    - routes
    - imagestreams
    - buildconfigs
    - jobs
    - groups
    - users
    - securitycontextconstraints
    - podsecuritypolicies
    verbs:
    - patch
    - update
  - apiGroups:
    - '*'
    attributeRestrictions: null
    resources:
    - jobs
    verbs:
    - delete
  - apiGroups:
    - '*'
    attributeRestrictions: null
    resources:
    - secrets
    verbs:
    - create
  - apiGroups:
    - '*'
    attributeRestrictions: null
    resourceNames:
    - vcs-autouser
    - gerrit-admin
    - jenkins-token
    - keycloak-admin
    - keycloak-gerrit
    - gerrit-project-creator
    - keycloak
    - keycloak-parameters
    - admin-console-client
    resources:
    - secrets
    verbs:
    - get
  - apiGroups:
    - "*"
    attributeRestrictions: null
    resourceNames:
    - edp-jenkins
    resources:
    - roles
    - rolebindings
    - clusterroles
    verbs:
    - patch
    - update
  - apiGroups:
    - '*'
    attributeRestrictions: null
    resources:
    - gitservers
    - gitservers/status
    - gitservers/finalizers
    - codebases
    - codebases/status
    - codebases/finalizers
    - codebasebranches
    - codebasebranches/status
    - codebasebranches/finalizers
    - codebaseimagestreams
    - codebaseimagestreams/status
    - codebaseimagestreams/finalizers
    - cdpipelines
    - cdpipelines/status
    - cdpipelines/finalizers
    - stages
    - stages/status
    - stages/finalizers
    - sonars
    - sonars/finalizers
    - sonars/status
    - nexuses
    - nexuses/finalizers
    - nexuses/status
    - adminconsoles
    - adminconsoles/finalizers
    - adminconsoles/status
    - gerrits
    - gerrits/finalizers
    - gerrits/status
    - jenkins
    - jenkins/finalizers
    - jenkins/status
    - jenkinses
    - jenkinses/finalizers
    - jenkinses/status
    - jenkinsserviceaccounts
    - jenkinsserviceaccounts/finalizers
    - jenkinsserviceaccounts/status
    - jenkinsscripts
    - jenkinsscripts/finalizers
    - jenkinsscripts/status
    - deployments/finalizers
    - deployments/finalizers.extensions
    - gerritreplicationconfigs
    - gerritreplicationconfigs/status
    - keycloaks
    - keycloaks/finalizers
    - keycloaks/status
    - keycloakclients
    - keycloakclients/finalizers
    - keycloakclients/status
    - keycloakrealms
    - keycloakrealms/finalizers
    - keycloakrealms/status
    - edpcomponents
    - edpcomponents/finalizers
    - edpcomponents/status
    verbs:
    - '*'
- apiVersion: security.openshift.io/v1
  kind: SecurityContextConstraints
  allowHostDirVolumePlugin: false
  allowHostIPC: false
  allowHostNetwork: false
  allowHostPID: false
  allowHostPorts: false
  allowPrivilegedContainer: false
  allowedCapabilities: null
  allowedFlexVolumes: null
  defaultAddCapabilities: null
  fsGroup:
    type: MustRunAs
    ranges:
      - min: 1
        max: 65543
  groups: []
  metadata:
    name: edp
  priority: null
  readOnlyRootFilesystem: false
  requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
  runAsUser:
    type: MustRunAsRange
    uidRangeMin: 1
    uidRangeMax: 65543
  seLinuxContext:
    type: MustRunAs
  supplementalGroups:
    type: RunAsAny
  users: []
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
parameters:
- displayName: Project to run edp-deploy
  description: Project EDP platform will be deployed from, default is edp-deploy
  name: PROJECT
  value: "edp-deploy"
  required: true
- displayName: Username that will run EDP deployment
  description: Username that EDP platform will be deployed from, default is admin
  name: USERNAME
  value: "admin"
  required: true