---
- set_fact:
    gerrit_project: "{{ (projects_suffix != '') | ternary('edp-' + projects_suffix, 'edp')}}"

- name: "Generate templates"
  vars:
    env_name: "{{ item }}"
    env_triggers: "{{ env_map[item].triggers }}"
  template:
    src: build-config.j2
    dest: "{{ templates_dir }}/{{ item }}-bc.json"
  with_items: "{{ env_map.keys() }}"

- name: "Create Pipelines in Openshift"
  command: |
   {{ ocadm }} -n {{ project_cicd }} apply -f {{ templates_dir }}/{{ item }}-bc.json
  with_items: "{{ env_map.keys() }}"

- name: "Generate deletion pipeline template"
  template:
    src: deletion-pipeline.j2
    dest: "{{ templates_dir }}/deletion-pipeline.json"

- name: "Create deletion pipeline in Openshift"
  command: |
   {{ ocadm }} -n {{ project_cicd }} apply -f {{ templates_dir }}/deletion-pipeline.json