apiVersion: v2
name: edp-install
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.16.0

dependencies:
- name: keycloak-operator
  version: "1.3.0-RC-4"
  repository: "@epamedp"

- name: codebase-operator
  version: "2.3.0-RC-14"
  repository: "@epamedp"

- name: jenkins-operator
  version: "2.3.0-RC-14"
  repository: "@epamedp"

- name: edp-component-operator
  version: "0.2.0-RC-3"
  repository: "@epamedp"

- name: cd-pipeline-operator
  version: "2.3.0-RC-4"
  repository: "@epamedp"

- name: nexus-operator
  version: "2.3.0-RC-5"
  repository: "@epamedp"

- name: sonar-operator
  version: "2.4.0-SNAPSHOT-50"
  repository: "@epamedp"

- name: admin-console-operator
  version: "2.3.0-RC-6"
  repository: "@epamedp"

- name: gerrit-operator
  version: "2.3.0-RC-4"
  repository: "@epamedp"

- name: reconciler
  version: "2.3.0-RC-15"
  repository: "@epamedp"