edp:
  name: "edp"
  platform: "openshift"
  version: "epamedp/edp-install:2.3.0"
  additionalToolsTemplate: "edp-install-template"
  superAdmins: ""
  admins: ""
  viewers: ""
  dnsWildCard: ""
  storageClass: "gp2"
  devDeploy: "false"
  keycloakNamespace: "security"
  keycloakUrl: ""
jenkins:
  version: "epamedp/edp-jenkins:2.3.0"
  volumeCapacity: "10Gi"
  stagesVersion: "release-2.4"
  pipelinesVersion: "release-2.4"
adminConsole:
  version: "epamedp/edp-admin-console:2.3.0"
perf:
  enabled: "false"
  nodeId: ""
  url: ""
