edp:
  name: "voronin-test"
  platform: "openshift"
  version: "epamedp/edp-install:latest"
  additionalToolsTemplate: "edp-install-template"
  superAdmins: "viktor_voronin@epam.com"
  admins: ""
  viewers: ""
  dnsWildCard: "delivery.aws.main.edp.projects.epam.com"
  storageClass: "gp2"
  devDeploy: "false"
  keycloakNamespace: "security"
  keycloakUrl: "https://keycloak-security.delivery.aws.main.edp.projects.epam.com"
  openshiftWebConsole: ""
jenkins:
  version: "epamedp/edp-jenkins:2.2.0"
  volumeCapacity: "10Gi"
  stagesVersion: "master"
  pipelinesVersion: "master"
adminConsole:
  version: "epamedp/edp-admin-console:2.2.1"
perf:
  enabled: "false"
  nodeId: ""
  url: ""
