edp:
  name: "tarianyk-helm-chart"
  platform: "openshift"
  version: "master-2.4.0-124"
  additionalToolsTemplate: "edp-install-template"
  superAdmins: "user3"
  admins:
    - "userOne"
    - "userTwo"
  developers:
    - "userThree"
  viewers: "user3"
  dnsWildCard: "delivery.aws.main.edp.projects.epam.com"
  storageClass: "gp2"
  devDeploy: "false"
  keycloakNamespace: "keycloak"
  keycloakUrl: "https://keycloak-keycloak.delivery.aws.main.edp.projects.epam.com"
  webConsole: "https://master.delivery.aws.main.edp.projects.epam.com"
  adminGroups:
    - "tarianyk-helm-chart-edp-admin"
  developerGroups:
    - "tarianyk-helm-chart-edp-developer"
  db:
    image: "postgres:9.6"
    name: edp-install-wizard-db
    port: 5432
    host:
    superAdminSecret:
      name: super-admin
      username: super-admin
    tenantAdminSecret:
      name: db-admin-console
      username: admin
    storage:
      class: gp2
      size: 2Gi
jenkins:
  storageClass: gp2
  name: "jenkins"
  version: "master-2.4.0-26"
  image: "docker-registry.default.svc:5000/oc-green-edp-cicd/edp-jenkins-master"
  volumeCapacity: "10Gi"
  stagesVersion: "master"
  pipelinesVersion: "master"
  sharedLibraryRepo:
    pipelines: "https://github.com/epmd-edp/edp-library-pipelines.git"
    stages: "https://github.com/epmd-edp/edp-library-stages.git"
  sharedLibraryVersion:
    pipelines: "master"
    stages: "master"
  pullSecrets:
adminConsole:
  version: "master-2.4.0-111"
  image: "docker-registry.default.svc:5000/oc-green-edp-cicd/edp-admin-console-master"
  pullSecrets:
perf:
  enabled: "false"
  nodeId: ""
  url: ""
vcs:
  enabled: "false"
keycloak:
  namespace: "keycloak"
  url: "https://keycloak-keycloak.delivery.aws.main.edp.projects.epam.com"
  secretToCopy: "keycloak"
jira:
  integration: true
  name: "epam-jira"
  rootUrl: "https://jiraeu.epam.com"
dockerRegistry:
  url: "093899590031.dkr.ecr.eu-central-1.amazonaws.com"

tags:
  keycloak-operator: true
  codebase-operator: true
  jenkins-operator: true
  edp-component-operator: true
  cd-pipeline-operator: true
  nexus-operator: true
  sonar-operator: true
  admin-console-operator: true
  gerrit-operator: true
  reconciler: true

keycloak-operator:
  namespace: "mm-helm-charts-test"
  image:
    name: docker-registry.default.svc:5000/oc-green-edp-cicd/keycloak-operator-master-dev-keycloak-operator-verified
    version: 1.4.0-SNAPSHOT.24

codebase-operator:
  namespace: "mm-helm-charts-test"
  image:
    name: docker-registry.default.svc:5000/oc-green-edp-cicd/codebase-operator-master-dev-codebase-operator-verified
    version: 2.4.0-SNAPSHOT.87
  jira:
    integration: true
    name: "epam-jira"
    apiUrl: "https://jiraeu-api.epam.com"
    rootUrl: "https://jiraeu.epam.com"
    credentialName: "epam-jira-user"

jenkins-operator:
  namespace: "mm-helm-charts-test"
  image:
    name: docker-registry.default.svc:5000/oc-green-edp-cicd/jenkins-operator-master-dev-jenkins-operator-verified
    version: 2.4.0-SNAPSHOT.97

edp-component-operator:
  namespace: "mm-helm-charts-test"

cd-pipeline-operator:
  namespace: "mm-helm-charts-test"
  image:
    name: docker-registry.default.svc:5000/oc-green-edp-cicd/cd-pipeline-operator-master-dev-cd-pipeline-operator-verified
    version: 2.4.0-SNAPSHOT.34

nexus-operator:
  namespace: "mm-helm-charts-test"
  image:
    name: docker-registry.default.svc:5000/oc-green-edp-cicd/nexus-operator-master-dev-nexus-operator-verified
    version: 2.4.0-SNAPSHOT.30
  nexus:
    deploy: true
    name: "nexus"
    image: "sonatype/nexus3"
    version: "3.21.2"
    dnsWildCard: "delivery.aws.main.edp.projects.epam.com"
    admins:
      - "userOne"
      - "userTwo"

sonar-operator:
  namespace: "mm-helm-charts-test"
  image:
    name: docker-registry.default.svc:5000/oc-green-edp-cicd/sonar-operator-master-dev-sonar-operator-verified
    version: 2.4.0-SNAPSHOT.50
  sonar:
    deploy: true
    name: "sonar"
    image: "sonarqube"
    version: "7.9-community"
    dnsWildCard: "delivery.aws.main.edp.projects.epam.com"

admin-console-operator:
  namespace: "mm-helm-charts-test"
  image:
    name: docker-registry.default.svc:5000/oc-green-edp-cicd/admin-console-operator-master-dev-admin-console-operator-verified
    version: 2.4.0-SNAPSHOT.30

gerrit-operator:
  namespace: "mm-helm-charts-test"
  image:
    name: docker-registry.default.svc:5000/oc-green-edp-cicd/gerrit-operator-master-dev-gerrit-operator-verified
    version: 2.4.0-SNAPSHOT.28
  gerrit:
    deploy: true
    name: "gerrit"
    image: "openfrontier/gerrit"
    sshPort: "30099"
    version: "3.1.4"
    admins:
      - "userOne"
      - "userTwo"
  gitServer:
    name: "gerrit"
    user: "jenkins"
    httpsPort: 443
    nameSshKeySecret: "gerrit-ciuser-sshkey"
    sshPort: 22
    dnsWildCard: "delivery.aws.main.edp.projects.epam.com"

reconciler:
  namespace: "mm-helm-charts-test"
  image:
    name: docker-registry.default.svc:5000/oc-green-edp-cicd/reconciler-master-dev-reconciler-verified
    version: 2.4.0-SNAPSHOT.45