edp:
  name: "tarianyk-helm-chart"
  platform: "openshift"
  version: "master-2.0.10"
  additionalToolsTemplate: "edp-install-template"
  superAdmins: "user3"
  admins:
    - "userOne"
    - "userTwo"
  developers:
    - "userThree"
  viewers: "user3"
  dnsWildCard: "delivery.aws.main.edp.projects.epam.com"
  storageClass: "gp2"
  devDeploy: "false"
  keycloakNamespace: "keycloak"
  keycloakUrl: "https://keycloak-keycloak.delivery.aws.main.edp.projects.epam.com"
  webConsole: "https://master.delivery.aws.main.edp.projects.epam.com"
  adminGroups:
    - "tarianyk-helm-chart-edp-admin"
  developerGroups:
    - "tarianyk-helm-chart-edp-developer"
  configMapName: "edp-config"
  db:
    image: "postgres:9.6"
    name: edp-install-wizard-db
    port: 5432
    host:
    superAdminSecret:
      name: super-admin-db
      username: super-admin
    tenantAdminSecret:
      name: db-admin-console
      username: admin
    storage:
      class: gp2
      size: 2Gi
jenkins:
  storageClass: gp2
  name: "jenkins"
  version: "epamedp/edp-jenkins:2.2.0"
  image: "docker-registry.default.svc:5000/tarianyk-helm-chart/edp-jenkins-2.2.0"
  volumeCapacity: "10Gi"
  stagesVersion: "master"
  pipelinesVersion: "master"
  sharedLibraryRepo:
    pipelines: "https://github.com/epmd-edp/edp-library-pipelines.git"
    stages: "https://github.com/epmd-edp/edp-library-stages.git"
  sharedLibraryVersion:
    pipelines: "master"
    stages: "master"
  pullSecrets:
adminConsole:
  version: "epamedp/edp-admin-console:2.2.1"
  image: "docker-registry.default.svc:5000/tarianyk-helm-chart/edp-admin-console-2.2.1"
  pullSecrets:
perf:
  enabled: "false"
  nodeId: ""
  url: ""
vcs:
  enabled: "false"
keycloak:
  namespace: "keycloak"
  url: "https://keycloak-keycloak.delivery.aws.main.edp.projects.epam.com"
  secretToCopy: "keycloak"
gerrit:
  deploy: true
  name: "gerrit"
  image: "openfrontier/gerrit"
  sshPort: "22"
  version: "3.1.4"
gitServer:
  name: "gerrit"
  user: "jenkins"
  httpsPort: 443
  nameSshKeySecret: "gerrit-ciuser-sshkey"
  sshPort: 22
jira:
  integration: true
  name: "epam-jira"
  apiUrl: "https://jiraeu-api.epam.com"
  rootUrl: "https://jiraeu.epam.com"
  credentialName: "epam-jira-user"
nexus:
  deploy: true
  name: "nexus"
  image: "sonatype/nexus3"
  version: "3.21.2"
sonar:
  deploy: true
  name: "sonar"
  image: "sonarqube"
  version: "7.9-community"
dockerRegistry:
  url: "093899590031.dkr.ecr.eu-central-1.amazonaws.com"
