{{- if not .Values.edp.db.host }}
  {{- if not (lookup "v1" "Service" ".Values.global.edpName" "edp-install-wizard-db").metadata }}
apiVersion: v1
kind: Service
metadata:
  name: edp-install-wizard-db
spec:
  ports:
    - name: db
      port: {{.Values.edp.db.port}}
      protocol: TCP
      targetPort: {{.Values.edp.db.port}}
  selector:
    app: edp-install-wizard-db
  type: ClusterIP
  {{end}}
{{end}}