{{- if not .Values.edp.db.host }}
  {{- if not (lookup "v1" "Secret" ".Values.edp.name" ".Values.edp.db.superAdminSecret.name").metadata }}
apiVersion: v1
data:
  password: {{ if .Values.edp.db.superAdminSecret.password }}{{ .Values.edp.db.superAdminSecret.password | b64enc }}{{else}}{{ randAlphaNum 10 | b64enc }} {{end}}
  username: {{.Values.edp.db.superAdminSecret.username | b64enc}}
kind: Secret
metadata:
  name: {{.Values.edp.db.superAdminSecret.name}}
type: Opaque
  {{end}}
{{end}}
