{{- if .Values.global.database.deploy }}
  {{- if not (lookup "v1" "PersistentVolumeClaim" ".Values.global.edpName" .Values.global.database.name).metadata }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.global.database.name}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.global.database.storage.size}}
  storageClassName: {{.Values.global.database.storage.class}}
  volumeMode: Filesystem
  {{end}}
{{end}}