kind: Template
apiVersion: v1
metadata:
  name: sonar
  annotations:
    description: |-
          The SonarQube template. sonar-db secret with credentials(database-name,database-password,database-user) for database access should be create before start.
          EXAMPLE: oc -n test-sonar-am create secret generic sonar-db --from-literal=database-user=test --from-literal=database-password=test
          NOTE: You must have persistent volumes available in your cluster to use this template.
    iconClass: icon-jenkins
    openshift.io/display-name: EDP Sonar (Persistent - gluster)
    tags: ci-cd
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/support-url: https://access.redhat.com
message: "Login to SonarQube with the default admin user: admin/admin"
objects:
{% if mr_deploy == 'false' %}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: sonar-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${SONAR_VOLUME_CAPACITY}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: sonar-db
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${SONAR_DB_CAPACITY}
{% endif %}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sonar
- apiVersion: v1
  kind: Service
  metadata:
    name: sonar
    labels:
      app: sonar
  spec:
    ports:
    - name: sonar
      port: 9000
    selector:
      app: sonar
- apiVersion: v1
  kind: Service
  metadata:
    name: sonar-db
    labels:
      app: sonar-db
  spec:
    ports:
    - name: sonar-db
      port: 5432
    selector:
      app: sonar-db
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for SonarQube's http service.
    name: sonar
    labels:
      app: sonar
  spec:
    to:
      kind: Service
      name: sonar
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: sonar
    name: sonar
  spec:
    replicas: 1
    selector:
      app: sonar
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: sonar
      spec:
        initContainers:
        - name: init-sonar-db
          image: busybox
          command: ["sh", "-c", "while ! nc -w 1 sonar-db 5432 </dev/null; do echo waiting for sonar-db; sleep 10; done;"]
        containers:
        - image: sonarqube:${SONAR_VERSION}
          imagePullPolicy: IfNotPresent
          name: sonar
          env:
          - name: SONARQUBE_JDBC_USERNAME
            valueFrom:
              secretKeyRef:
                name: sonar-db
                key: database-user
          - name: SONARQUBE_JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sonar-db
                key: database-password
          - name: SONARQUBE_JDBC_URL
            value: jdbc:postgresql://sonar-db/sonar
          ports:
          - containerPort: 9000
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            httpGet:
              port: 9000
              path: /
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            httpGet:
              port: 9000
              path: /
            timeoutSeconds: 5
          terminationMessagePath: /dev/termination-log
          resources:
            requests:
              memory: 1Gi
          volumeMounts:
          - mountPath: /opt/sonarqube/extensions/plugins
            name: sonar-data
        serviceAccount: sonar
        volumes:
        - name: sonar-data
{% if mr_deploy == 'false' %}
          persistentVolumeClaim:
            claimName: sonar-data
{% else %}
          emptyDir: {}
{% endif %}
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: sonar
    name: sonar-db
  spec:
    replicas: 1
    selector:
      app: sonar-db
    strategy:
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: sonar-db
      spec:
        containers:
        - name: sonar-db
          env:
          - name: POSTGRES_DB
            value: "sonar"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: sonar-db
                key: database-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sonar-db
                key: database-password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POD_IP
            valueFrom: { fieldRef: { fieldPath: status.podIP } }
          image: postgres:9.6
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1Gi
          ports:
            - containerPort: 5432
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            initialDelaySeconds: 60
            timeoutSeconds: 3
            periodSeconds: 5
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: sonar-db
        serviceAccount: sonar
        volumes:
        - name: sonar-db
{% if mr_deploy == 'false' %}
          persistentVolumeClaim:
            claimName: sonar-db
{% else %}
          emptyDir: {}
{% endif %}
parameters:
- displayName: SonarQube version
  value: "7.1"
  name: SONAR_VERSION
- description: Volume space available for SonarQube
  displayName: SonarQube Volume Capacity
  name: SONAR_VOLUME_CAPACITY
  value: 1Gi
- description: Volume space available for SonarQube Database
  displayName: SonarQube database Volume Capacity
  name: SONAR_DB_CAPACITY
  value: 2Gi
