# Copyright 2018 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

---
- include_tasks: roles/api/vcs/get-token.yml
  with_items:
    - { hostname: '{{ project_vcs_hostname_url }}', username: '{{ vcs_auto_user_login }}', password: '{{ vcs_auto_user_password }}' }

- include_tasks: roles/api/vcs/check-project-exists.yml
  with_items:
    - { hostname: '{{ project_vcs_hostname_url }}', project_path: "{{ vcs_project_path }}", csrf_token: '{{ csrf_token }}' }

- block:
  - include_tasks: roles/api/vcs/get-group-id-by-name.yml
    with_items:
      - { hostname: '{{ project_vcs_hostname_url }}', group_name: "{{ project_vcs_group_path | replace('/', '%2F') }}", csrf_token: '{{ csrf_token }}' }

  - include_tasks: roles/api/vcs/create-project.yml
    with_items:
      - { hostname: '{{ project_vcs_hostname_url }}', project_name: "{{ vcs_project_name }}", group_name: "{{ project_vcs_group_path }}", group_id: "{{ vcs_group_id }}", csrf_token: '{{ csrf_token }}' }
  when: repository_exists | bool == false

