{{- if .Values.jira.integration -}}
  {{- if not (lookup "v2.edp.epam.com/v1alpha1" "JiraServer" .Values.edp.name .Values.jira.name).metadata }}
apiVersion: v2.edp.epam.com/v1alpha1
kind: JiraServer
metadata:
  name: {{.Values.jira.name}}
spec:
  apiUrl: {{.Values.jira.apiUrl}}
  rootUrl: {{.Values.jira.rootUrl}}
  credentialName: {{.Values.jira.credentialName}}
  {{end}}
{{end}}