{{- if .Values.additionalTemplates.sonar.deploy -}}
  {{- if not (lookup "v2.edp.epam.com/v1alpha1" "Sonar" .Values.edp.name .Values.additionalTemplates.sonar.name).metadata }}
apiVersion: v2.edp.epam.com/v1alpha1
kind: Sonar
metadata:
  name: {{.Values.additionalTemplates.sonar.name}}
spec:
  edpSpec:
    dnsWildcard: {{ .Values.edp.dnsWildCard }}
  type: Sonar
  image: {{.Values.additionalTemplates.sonar.image}}
  version: {{.Values.additionalTemplates.sonar.version}}
  volumes:
    - capacity: 1Gi
      name: data
      storage_class: gp2
    - capacity: 1Gi
      name: db
      storage_class: gp2
  {{end}}
{{end}}