---
- name: "Get autouser secret name from user-settings cm"
  shell: |
   {{ ocadm }} -n {{ project_cicd }} get cm user-settings -o=jsonpath='{ .data.gitlab_autouser_secret }'
  register: secret_name

- name: "Get ssh key from cicd projects secret"
  shell: >
    {{ ocadm }} --namespace {{ project_cicd }} get secret {{ secret_name.stdout }}
    --template={% raw %}'{{ index .data "ssh-privatekey" }}'{% endraw %} | base64 --decode
  register: ssh_key

- local_action: copy content={{ ssh_key.stdout }} dest={{ target_file }} mode=0400