---
- name: "Get ssh key from cicd projects secret"
  shell: >
    {{ ocadm }} --namespace {{ project_cicd }} get secret {{ gitlab_auto_user_secret }}
    --template={% raw %}'{{ index .data "ssh-privatekey" }}'{% endraw %} | base64 --decode
  register: ssh_key

- local_action: copy content={{ ssh_key.stdout }} dest={{ work_dir }}/private.key mode=0400