---
- name: "Get gerrit-admin ssh key from secret"
  shell: |
    {{ ocadm }} -n {{ project_cicd }} get secret gerrit-admin --template={% raw %}'{{ index .data "id_admin_rsa" }}'{% endraw %} | base64 --decode
  register: gerrit_admin_ssh

- local_action: copy content={{ gerrit_admin_ssh.stdout }} dest={{ work_dir }}/gerrit_admin.key mode=0400

- name: "Create .ssh directory"
  file:
    path: ~/.ssh
    state: directory

- name: "Config ssh"
  copy:
    content: |
      Host gerrit*
        HostName gerrit.{{ project_cicd }}
        User admin
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        IdentityFile {{ work_dir }}/gerrit_admin.key
        IdentitiesOnly yes

      Host {{ gitlab_host }}
        HostName {{ gitlab_host }}
        User git
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        IdentityFile {{ work_dir }}/private.key
        IdentitiesOnly yes
    dest: ~/.ssh/config
    force: no

- name: "Get gerrit ssh port"
  shell: "{{ ocadm }} -n {{ project_cicd }} get configMap gerrit -o=jsonpath={.data.sshPort}"
  register: "gerrit_ssh_port"

- name: "Create project in Gerrit"
  shell: "ssh -p {{ gerrit_ssh_port.stdout }} admin@gerrit.{{ project_cicd }} gerrit create-project {{ project_name }}"
