--- # Jenkins full installation
- name: "Copy Jenkins template"
  template:
    src: "{{ item }}"
    dest: "{{ templates_dir }}/jenkins/{{ item }}"
  with_items:
    - "jenkins-{{ tools.jenkins.fs_type }}.yaml"

- name: "Install Jenkins app"
  command: |
    {{ ocadm }} -n {{ project_cicd }} new-app -f {{ templates_dir }}/jenkins/jenkins-{{ tools.jenkins.fs_type }}.yaml
    -p JENKINS_PASSWORD={{ tools.jenkins.password }}
    -p JENKINS_ENABLE_OAUTH={{ tools.jenkins.enable_oauth }}
    -p JENKINS_MAVEN_CACHE_VOLUME_CAPACITY={{ tools.jenkins.maven_cache_volume_capacity }}
    -p JENKINS_FRONTEND_IMAGE={{ tools.jenkins.frontend_image }}
    -p JENKINS_IMAGE_VERSION={{ tools.jenkins.jenkins_image }}
    -p JENKINS_BACKEND_IMAGE={{ tools.jenkins.backend_image }}
    -p JENKINS_UI_URL={{ tools.jenkins.web_url }}
    {{ '-p JENKINS_HOST_PATH_VOLUME=' + tools.jenkins.host_path_volume if tools.jenkins.fs_type=='hostpath' else '-p JENKINS_VOLUME_CAPACITY=' + tools.jenkins.volume_capacity }}
    -p STORAGE_CLASS_NAME={{ storage_class_name }}
  register: result
  ignore_errors: true
  changed_when: '"already" not in result.stderr'
  failed_when:
    - 'result.rc != 0'
    - '"already" not in result.stderr'
