- name: "Get crumb from Jenkins"
  uri:
    url: http://jenkins.{{ project_cicd }}:8080/crumbIssuer/api/json
    method: GET
    user: admin
    password: "{{ tools.jenkins.admin_token }}"
    force_basic_auth: yes
  register: result
  retries: 5
  delay: 1

- set_fact:
    jenkins_crumb: "{{ result.json.crumb }}"
