- name: "Retrieve {{ item.username }} user API token from Jenkins"
  vars:
    retrieve_token_script: |
      import jenkins.security.*
      User user = User.get('{{ item.username }}')
      ApiTokenProperty t = user.getProperty(ApiTokenProperty.class)
      def token = t.getApiTokenInsecure()
      println(token)
  jenkins_script:
    script: "{{ retrieve_token_script}}"
    user: admin
    password: "{{ tools.jenkins.password }}"
    url: http://jenkins.{{ project_cicd }}:8080
  register: result

- set_fact:
    jenkins_token: "{{ result.output }}"

- name: "Create secret for {{ item.username }} user with API token"
  register: result
  ignore_errors: true
  shell: >
    {{ ocadm }} -n {{ project_cicd }} create secret generic jenkins-token
    --from-literal=username={{ item.username }}
    --from-literal=token={{ jenkins_token }}
  changed_when: '"already" not in result.stderr'
  failed_when:
    - 'result.rc != 0'
    - '"already" not in result.stderr'