{{- if not (lookup "v1" "ConfigMap" ".Values.global.edpName" "edp-config").metadata }}
apiVersion: v1
data:
  edp_name: {{ .Values.global.edpName }}
  edp_version: {{.Values.global.version}}
  dns_wildcard: {{ .Values.global.dnsWildCard }}
  perf_integration_enabled: "{{ .Values.perf.enabled }}"
  vcs_integration_enabled: "{{ .Values.vcs.enabled }}"
  adminGroups: {{ join "," .Values.edp.adminGroups }}
  developerGroups: {{ join "," .Values.edp.developerGroups }}
kind: ConfigMap
metadata:
  name: edp-config
{{end}}