{{- if not (lookup "v1" "ConfigMap" ".Values.global.edpName" "edp-config").metadata }}
apiVersion: v1
data:
  edp_name: {{ .Values.global.edpName }}
  edp_version: {{.Values.edp.version}}
  dns_wildcard: {{ .Values.global.dnsWildCard }}
  perf_integration_enabled: "{{ .Values.perf.enabled }}"
  vcs_integration_enabled: "{{ .Values.vcs.enabled }}"
kind: ConfigMap
metadata:
  name: edp-config
{{end}}