---
- name: "Set project_cicd variable"
  set_fact:
    project_cicd: "{{ lookup('env','PROJECT_CICD') }}"

- include_tasks: roles/common/tasks/import-from-git-to-gerrit.yml

- include_tasks: roles/common/tasks/update-project-settings.yml

- include_tasks: roles/common/tasks/manage-jenkins/trigger-job-provisioning.yml

- include_tasks: roles/common/tasks/manage-openshift/create-template.yml