---
- name: "Get current app.settings.json value"
  command: |
    {{ ocadm }} get cm project-settings -n {{ project_cicd }} -o json
  register: output

- set_fact:
     app_settings_json: "{{ output.stdout | from_json }}"

- copy:
    content: "{{ app_settings_json }}"
    dest: "/tmp/old_cm.json"

- template:
    src: "update-cm-data.j2"
    dest: "/tmp/update-cm-data.py"

- name: "Update app.settings.json value"
  shell: >
   python /tmp/update-cm-data.py --git_repo {{ gitlab_url }} --name {{ app_name }} --language {{ language }}
   --tool {{ build_tool }} --framework {{ framework }} --need_route {{ route }}
  register: pythonOutput

- name: "Replace app.settings.json with new values"
  command: |
   {{ ocadm }} replace --namespace {{ project_cicd }} -f /tmp/updated_cm.json

- name: "Get crumb from Jenkins"
  uri:
    url: https://jenkins.{{ project_cicd_name }}:8080/crumbIssuer/api/json
    method: GET
    user: admin
    password: "{{ tools.jenkins.password }}"
    force_basic_auth: yes
  register: crumb

- name: "Trigger job provisioning"
  uri:
    url: https://jenkins.{{ project_cicd_name }}:8080/job/jobsprovisioning/build
    method: POST
    user: admin
    password: "{{ tools.jenkins.password }}"
    force_basic_auth: yes
    HEADER_Jenkins-Crumb: "{{ crumb.json.crumb }}"
    status_code: 201

- name: "Remove temp files"
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /tmp/update-cm-data.py
    - /tmp/old_cm.json
    - /tmp/updated_cm.json