{{- if not (lookup "v1" "v1.edp.epam.com/v1alpha1" .Values.edp.name "main").metadata }}
apiVersion: v1.edp.epam.com/v1alpha1
kind: Keycloak
metadata:
  name: "main"
spec:
  url: {{ .Values.keycloak.url }}
  secret: "keycloak-main-secret"
  users:
  {{- range .Values.edp.admins }}
    - username: {{.}}
      realmRoles:
        - administrator
  {{- end}}
  {{- range .Values.edp.developers }}
    - username: {{.}}
      realmRoles:
        - developer
  {{- end}}
{{end}}