{{- if not (lookup "v1" "Secret" ".Values.edp.name" "keycloak-main-secret").metadata }}
apiVersion: v1
data:
  {{- $data := (lookup "v1" "Secret" .Values.keycloak.namespace .Values.keycloak.secretToCopy).data }}
  username: {{$data.username}}
  password: {{$data.password}}
kind: Secret
metadata:
  name: "keycloak-main-secret"
type: Opaque
{{end}}